### ISSUE TITLE
Use typesense behind subpath proxy

### ISSUE THREAD

**Issue by CrashLaker** [typesense/typesense-python#11]
I'm willing to set this behing a subpath proxy.

Something like http://host/path -> http://<typesense-ip>:8108

As I can see from https://github.com/typesense/typesense-python/blob/1ac9d74694dc97c10f1c18a23498e7b4bb142063/typesense/configuration.py#L19 it won't let me set a subpath.

**Actual behaviour**

```python
client = typesense.Client({
  'api_key': 'xyz',
  'nodes': [{
    'host': 'host/subpath',
    'port': '',
    'protocol': 'http',
  }],
  'connection_timeout_seconds': 2
})
```

this yields to 

```python
client.api_call.get_node().url()
# http://host/subpath:
```

**Expected behaviour**
```python
client.api_call.get_node().url()
# http://host/subpath
# without :
```

**Comment by kishorenc** [comment]
@CrashLaker This should work:

```
client = typesense.Client({
    'api_key': 'abcd',
    'nodes': [{
        'protocol': 'http',
        'host': 'proxy_host',
        'port': '80',
        'path': '/dir',
    }],
    'connection_timeout_seconds': 2
})

print(client.api_call.get_node().url())
```

```
http://proxy_host:80/dir
```

Or use `443` for HTTPS.

**Comment by CrashLaker** [comment]
thank you @kishorenc 
i didn't see `self.path` there
