### ISSUE TITLE
Possible to have multiple clients active at the same time?

### ISSUE THREAD

**Issue by zehawki** [typesense/typesense-python#28]
So right now I have this:

```
typesense_client = typesense.Client({
	'api_key': settings.TYPESENSE_PRIVATE_KEY,
	'nodes': [{
		'host': <some server URL here>,
		'port': '443',
		'protocol': 'https'
	}],
	'connection_timeout_seconds': 2
})
```

Can I simultaneously have a `typesense_client2` (or more) to other servers and use those in parallel? Will anything break in this package due to such usage?

**Comment by kishorenc** [comment]
Yes, this is fine to do. The client is just a thin wrapper around the HTTP API so you can create multiple clients without any issues.
