### ISSUE TITLE
Import function does not accept a boolean for the return_id parameter

### ISSUE THREAD

**Issue by kevinj507** [typesense/typesense-python#34]
## Description

When using documents.import_(), it seems that specifying the return_id parameter as a boolean does not work but making it a string works. 

## Steps to reproduce

The following line will work:
res = client.collections['entities'].documents.import_(jsonl_file.read().encode('utf-8'), {'action': 'upsert', "return_id": "true"})

The following line will not work:
res = client.collections['entities'].documents.import_(jsonl_file.read().encode('utf-8'), {'action': 'upsert', "return_id": True})

## Expected Behavior

res = client.collections['entities'].documents.import_(jsonl_file.read().encode('utf-8'), {'action': 'upsert', "return_id": True})

I'm expecting this to work since based on the documentation and common sense it feels more accurate than passing in "true", the string value. 

## Actual Behavior

[Errno 400] Parameter `return_id` must be a true|false.

## Metadata

**Typesense Version**: 0.15.1

**OS**: ubuntu 22.04

**Comment by kishorenc** [comment]
Fixed  by https://github.com/typesense/typesense-python/commit/66ec088c98b3caaf7da5f5c355a83464235bbe26
