### ISSUE TITLE
Please publish sdist

### ISSUE THREAD

**Issue by grantjenks** [typesense/typesense-python#38]
## Description

Please publish the sdist per #37 to PyPI. I’ve got to get unblocked and I don’t want to publish a new package like typesense-sdist myself. 

## Steps to reproduce

Pip install source dist of Typesense.

## Expected Behavior

Install works.

## Actual Behavior

Install fails due to missing sdist.

## Metadata

**Typesense Version**: 0.16.0

**OS**: Linux

**Comment by grantjenks** [comment]
I'm planning to publish an sdist this Friday to PyPI but I'd much rather you publish v0.16.0 instead.

**Comment by kishorenc** [comment]
I've published `0.17.0`.

**Comment by grantjenks** [comment]
Thank you!
