### ISSUE TITLE
Can't ignore ssl checks or add a trusted ssl certificate to the requests

### ISSUE THREAD

**Issue by arjolpanci** [typesense/typesense-python#42]
## Description

I have a typesense server deployed to openshift (within the same network I am trying to run the application from).
If I try to reach that server with curl or postman, I am able to do so, however in python all requests fail with an SSLError.

I tried to make a request to the api myself with the "verify=False" flag, and it works. But I cannot configure the client to do the same (nor supply the certificate to trust).

## Steps to reproduce

Have a typesense server deployed to a remote hostname with https, and try to configure the client like so :

![image](https://github.com/typesense/typesense-python/assets/16520125/367f329f-bc4a-449d-888a-f951ea21f829)

Try to access anything from the client that would require an api call.

## Expected Behavior

The client has configuration options to skip ssl verifications or add trusted certificates

## Actual Behavior

It is not possible to make the client skip certificate verification during request calls.

Error :

`requests.exceptions.SSLError: HTTPSConnectionPool(host='<url-here>', port=443): Max retries exceeded with url: /collections (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))`

## Metadata

**Typesense Version**: 25.1

**OS**: Running on linux container

**Comment by eliskovets** [comment]
Hello @kishorenc , 
I've created a PR to fix this issue and would appreciate if you can take a look at https://github.com/typesense/typesense-python/pull/46

Thank you!

**Comment by arjolpanci** [comment]
> Hello @kishorenc , I've created a PR to fix this issue and would appreciate if you can take a look at #46
> 
> Thank you!

Apologies for the late reply. I had forgotten about this issue because I ended up using a locally modified version of the client with similar changes to what you have made in the PR.

Thank you
