### ISSUE TITLE
Hope to support Chinese and Japanese etc.

### ISSUE THREAD

**Issue by willowHB** [typesense/typesense-python#9]
## Description
Hope to support Chinese and Japanese etc.
## Steps to reproduce
When I tap Japanese；error is “UnicodeEncodeError: 'latin-1' codec can't encode characters in position 70-76: Body ('ハリーポッター') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.”
then，I encode the json ，like ".encode('utf-8')";
error  is "TypeError: Object of type bytes is not JSON serializable"

## Metadata

**Typsense Version**:
 v0.19.0
**OS**:
Centos 8

**Comment by kishorenc** [comment]
@willowHB 

Can you please post the exact Python client code snippet that's causing this encoding issue? That would be very helpful. 

Also, Typesense as of v0.19 does not officially support Japanese or other languages that do not use a space for separating words. However, we are adding beta support Japanese in the next release so we can use this issue to discuss that and I can get your feedback also.

**Comment by willowHB** [comment]
Thats cool！
The following is my test code.

import json
import random

import typesense

# 初始化客户端
client = typesense.Client({
    'nodes': [{
        'host': '172.18.18.14',
        'port': '8108',
        'protocol': 'http'
    }],
    'api_key': 'abcd',
    'connection_timeout_seconds': 2
})

# 创建Collection
# books_schema = {
#     'name': 'books',
#     'fields': [
#         {'name': 'title', 'type': 'string'},
#         {'name': 'authors', 'type': 'string[]'},
#         {'name': 'image_url', 'type': 'string'},
#
#         {'name': 'publication_year', 'type': 'int32'},
#         {'name': 'ratings_count', 'type': 'int32'},
#         {'name': 'average_rating', 'type': 'float'},
#
#         {'name': 'authors_facet', 'type': 'string[]', 'facet': True},
#         {'name': 'publication_year_facet', 'type': 'string', 'facet': True},
#     ],
#     'default_sorting_field': 'ratings_count'
# }
#
# client.collections.create(books_schema)

# add to Collection
with open('../temp/books.jsonl', 'r+', encoding='utf-8') as infile:

    for json_line in infile:

        dumps = json.dumps(json_line, ensure_ascii=False)
        print('这是dumps后的json数据：', dumps)

        book_document = json.loads(dumps)
        for i in range(1, 2):
            print(i)
            randint = random.randint(0, 9999999999999)
            print(randint)
            document_new = book_document.replace("xxoo", "No." + str(randint)).encode('utf-8')
            print('这是文件中的json数据：', book_document)
            print('这是文件中的json数据编码后：', document_new)
            print('这是读取到文件数据的数据类型：', type(book_document))
            s = str(document_new, encoding='utf-8')
            print('这是Str：', s)
            print('这是Str：', type(s))

            client.collections['books'].documents.create(book_document)

            ssss = {
                "title": "Harry Potter and the Chamber of Secrets [Paperback] J K ハリーポッター No.9038178032878",
                "authors": [
                    "J. K. Rowling"
                ],
                "image_url": "https://images-na.ssl-images-amazon.com/images/I/61aWJsEoKfL._SX324_BO1,204,203,200_.jpg",
                "publication_year": 2002,
                "ratings_count": 9,
                "average_rating": 5.0,
                "authors_facet": [
                    "J. K. Rowling"
                ],
                "publication_year_facet": "2020"
            }


# 读取String
# for json_line in infile:
# book_document = json.loads(json_line)
# 或者 loads 和 load 区别
# 读取json
# book_document = json.load(json_line)

# search1
search_parameters = {
    'q': 'harry',
    'query_by': 'title',
    'sort_by': 'ratings_count:desc'
}

documents_search = client.collections['books'].documents.search(search_parameters)

print(documents_search)

# search2
search_parameters = {
    'q': 'harry',
    'query_by': 'title',
    'sort_by': 'publication_year:desc'
}

search = client.collections['books'].documents.search(search_parameters)

print(search)

**Comment by kishorenc** [comment]
@willowHB This is fixed in the latest update to the client in `0.12.0`.
